### ISSUE TITLE
Downloading long mangas from Mangapark

### ISSUE THREAD

**Issue by janfett** [darkdragn/mangaGet2#1]
For mangas with > 100 pages, from _mangapark_, only the first hundred pages are downloaded (e.g. in vol. 8 and vol. 9 of high school girls). 

I suspect this is because mangapark loads page numbers > 101 on demand only after the user scrolls  down. It would be good to have a workaround for this if possible.

**Comment by darkdragn** [comment]
Definitely. I'll take a look and start working on this either today or
tomorrow.

**Comment by darkdragn** [comment]
Just finished commiting a fix. After 100 pages they were flooding the src tag with a blank.gif, and putting the actual image url in a data-original tag. It's up and running right now, and I tested it with the chapter you recommended (High school girls, latest chapter with 182 pages.)
